### ISSUE TITLE
Issue on page /REVIEWING.html

### ISSUE THREAD

**Issue by ellacharmed** [aimakerspace/ai-practitioner-handbook#129]
As an external audience, I don't have access to the Google drive link to the book cited at the bottom of this page. Should that link go to Amazon, perhaps? Or NLB? 
Or, any other major source where the book is available to be purchased/borrowed.

**Comment by chuawjk** [comment]
Thanks @ellacharmed for the feedback, and for reading our handbook! I've updated to link to point to the book's [official website](https://docsfordevelopers.com/), which in turn points to a few places where the book is available for purchase. Will be updating the link when we push our next round of handbook content.
