### ISSUE TITLE
How does the AI engineer translate the business challenge into an AI problem?

### ISSUE THREAD

**Issue by tankwanchet** [aimakerspace/ai-practitioner-handbook#21]
**Section Outline**
This section entails the information/knowledge that AI Engineer should acquire to translate the business challenge into an AI problem.

- Introduction
- Translation of Business Requirements into Technical Requirements

**Definition of Done**
- [x] Completed `<chapter-num>/<filename.md>`
- [x] Verified against [self-review checklist](https://docs.google.com/document/d/1jIFbca53uD8b2FsDrUR6Dlb7k20SlZQBt-jpJ_qV14Y/edit)
- [x] Page builds and displays correctly

**Comment by tankwanchet** [comment]
As discussed with @chuawjk , the section will be renamed: "What information/knowledge should AI engineer acquire from the presales team?" to "How does the AI engineer translate the business challenge into an AI problem?".  The reason for doing so is that the initial question is too broad for a section. So changing the question into one that is specific will be ideal.

**Comment by chuawjk** [comment]
Thanks @tankwanchet for your contributions!

I like how this provides a systematic framework to this translation process. The illustrative example helps to contextualise the framework as well.

Some suggestions:
1. Engineers might have the misconception that translating business challenge to an AI problem is solely the task of the presales consultant. It would be helpful to explain why engineers also need to possess similar skills.
2. Minor grammar/formatting issues:
    a. Capitalisation at L33:
    ```
    what is the main task that you are keen to replace?
    ```
    b. Tenses at L38:
    Original:
    ```
    Now, you will have gain an understanding into the business challenge and the AI problem.
    ```
    Suggested:
    ```
    Now, you would have gained an understanding of the business challenge and the AI problem.
    ```
    
The heads might have views regarding my first suggestion, so perhaps you want to wait to hear them out during Sprint Review before making the relevant edits.

**Comment by tankwanchet** [comment]
@chuawjk 

Thank you for the feedback! I disagree with your point on first suggestion being presales consultant's problem as it was written in a generic manner that would be applicable to an AI engineer. Translation is an important skill that contributes to building the AI solution in a project. For example, during the early stages of a AI project, AI engineer is still exploring the data and methodologies that can best tackle the AI problem. The AI engineer can translate the problem statement into different technical requirements and therefore, derive potential solutions or approaches to be decided upon for development.

**Comment by chuawjk** [comment]
@tankwanchet 

Just realised that I had mistakenly placed my comment here instead of the PR. My bad! Will continue the discussion here for continuity.

```
I disagree with your point on first suggestion being presales consultant's problem 
```
That was actually not the point I was trying to make. In fact, I fully agree with you that translation is a skill that's also _important for engineers_. I was just concerned that readers (esp new engineers) might _mistakenly_ see this as something outside an engineer's job scope, so this misconception could potentially be anticipated and addressed in the text.

The elaboration you provided definitely helps to clarify this potential misconception that readers might have. We can work together to find a way to work it into the text.
```
For example, during the early stages of a AI project, AI engineer is still exploring the data and methodologies that can best tackle the AI problem. The AI engineer can translate the problem statement into different technical requirements and therefore, derive potential solutions or approaches to be decided upon for development.
```
