### ISSUE TITLE
Question you are responding to

### ISSUE THREAD

**Issue by shafirahmad** [aimakerspace/ai-practitioner-handbook#83]
**Section Outline**
Please list the key points of content you intend to cover for this section
 
 
**Definition of Done**
- [ ] Completed `2-proj-mgmt-tech-lead/translate-technical-jargon.md`
- [ ] Verified against [self-review checklist](https://github.com/aisingapore/ai-practitioner-handbook/blob/main/REVIEWING.md)
- [ ] Added section to [table of contents](https://github.com/aisingapore/ai-practitioner-handbook/blob/main/_toc.yml)
- [ ] Page builds and displays correctly on local machine

**Comment by chuawjk** [comment]
@shafirahmad This issue looks like a duplicate of #74. Can I close this?

**Comment by shafirahmad** [comment]
Duplicate of #74
